routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/test', function () {
   return  'echo <?php {{asset("css/app.css")}}?>;';
});
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

*/

Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    Route::resource('users', 'UsersController');
    Route::resource('hbg', 'HbgController');
    Route::resource('sct', 'SubcontractorTradesController');

// ------------------API-----------------//
    Route::get('getScts', 'UsersController@getScts');
    Route::get('getUser', 'UsersController@getUser');
    Route::post('saveUser', 'UsersController@saveUser');
    Route::post('createUser', 'UsersController@createUser');
    Route::post('saveCompany', 'UsersController@saveCompany');

    Route::post('getHbgs', ['uses' => 'HbgController@getHbgs', 'as' => 'hbg.getHbgs']);
    Route::post('changeSct', ['uses' => 'HbgController@changeSct', 'as' => 'hbg.changeSct']);
    Route::post('changeIsTrade', ['uses' => 'HbgController@changeIsTrade', 'as' => 'hbg.changeIsTrade']);
    Route::post('getScts', ['uses' => 'SubcontractorTradesController@getScts', 'as' => 'sct.getScts']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;
use App\Models\Subcontractors\Subcontractors;
use App\Models\CompanyInfo\Profile;
use App\Models\Post;

class User extends Authenticatable implements CanResetPasswordContract
{
    use Notifiable, CanResetPassword, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'password',
        'password_confirmation',
        'userType',
        'verified',
        'isSubContractor',
        'isBuilder',
        'is_terms_accepted',
        'is_tutorial_viewed',
        'associations',
        'certifications',
        'references'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'password_confirmation'
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    /**
     * Relation with companies.
     */
    public function company_info()
    {
        return $this->hasOne(CompanyInfo::class, 'userID');
    }

    /**
     * Relation with Subcontractors.
     */
    public function trade_info()
    {
        return $this->hasOne(Subcontractors::class, 'userID');
    }

    /**
     * Relation with Profile.
     */
    public function profile()
    {
        return $this->hasOne(Profile::class, 'userID');
    }

    /**
     * Relation with Post.
     */
    public function posts()
    {
        return $this->hasMany(Post::class, 'userID');
    }
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests\User\UserUpdate;
use App\Http\Requests\User\UserCreate;
use App\Http\Requests\User\CompanyUpdate;

use App\User;
use App\CompanyInfo;
use App\Models\Subcontractors\SubcontractorTrades;
use App\Models\Subcontractors\Subcontractors;
use App\Models\Builder\Builders;
use App\Models\CompanyInfo\Profile;
use App\Models\CompanyInfo\ProfileUploads;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Password;
use Webpatser\Uuid\Uuid;
use Bouncer;
use App\Helpers\GeneralHelpers;
use App\Helpers\DBHelpers;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Auth\Events\Registered;
use Prologue\Alerts\Facades\Alert;

class UsersController extends Controller
{
    /**
     * @var User
     */
    private $user;

    /**
     * @var CompanyInfo
     */
    private $company_info;

    /**
     * @var SubcontractorTrades
     */
    private $subcontractorTrades;

    /**
     * @var Subcontractors
     */
    private $subcontractors;

    /**
     * @var Builders
     */
    private $builders;

    /**
     * UsersController constructor.
     *
     * @param User $user
     * @param SubcontractorTrades $subcontractorTrades
     * @param CompanyInfo $company_info
     * @param Subcontractors $subcontractors
     * @param Builders $builders
     */
    public function __construct(User $user, SubcontractorTrades $subcontractorTrades, CompanyInfo $company_info, Subcontractors $subcontractors, Builders $builders)
    {
        $this->user = $user;
        $this->subcontractorTrades = $subcontractorTrades;
        $this->company_info = $company_info;
        $this->subcontractors = $subcontractors;
        $this->builders = $builders;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = $this->user->with(['company_info', 'trade_info', 'trade_info.subcontractor_trades'])->get();
        
        return view('dashboard.users.index', [
            'users' => $users
        ]);
    }

    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(int $id)
    {
        return view('dashboard.users.edit', [ 
            'id' => $id
        ]);
    }

    /**
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('dashboard.users.create', [ 
        ]);
    }

    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function destroy(int $id)
    {
        $this->user->findOrFail($id)->delete();
        Alert::success('User successfully deleted')->flash();
        return redirect()->route('users.index')->with('alerts', Alert::all());
    }

// ------------------API-----------------//
    /**
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function getUser(Request $request)
    {
        $id = $request->get('id');
        $user = $this->user->with(['company_info', 'trade_info'])->findOrFail($id);

        return response()->json(['user' => $user], 200);
    }

    /**
     * @param UserUpdate $request
     *
     * @return JsonResponse
     */
    public function saveUser(UserUpdate $request)
    {
        $id = $request->get('id');
        $user = $this->user->findOrFail($id);

        $user->update($request->validatedOnly());
        if ($user->userType === 'subcontractor') {
            try {
                $subcontractor = $this->subcontractors->findOrFail($id);
                $subcontractor->update($request->get('trade_info'));
            }
            catch(ModelNotFoundException $e){}
        }
        $user = $this->user->with(['company_info', 'trade_info'])->findOrFail($id);
        return response()->json(['message' => 'User successfully updated', 'user' => $user]);
    }

    /**
     * @param CompanyUpdate $request
     *
     * @return JsonResponse
     */
    public function saveCompany(CompanyUpdate $request)
    {
        $id = $request->get('userID');
        $company_info = $this->company_info->findOrFail($id);
        $validatedReq = $request->validatedOnly();
        $validatedReq['companySlug'] = str_slug(str_replace('&', 'and', $validatedReq['company']));
        $company_info->update($validatedReq);        
        return response()->json(['message' => 'Company successfully updated', 'company_info' => $company_info]);
    }

    /**
     * @param UserCreate $request
     *
     * @return JsonResponse
     */
    public function createUser(UserCreate $request)
    {
        $user = new User;
        $sc = new Subcontractors();
        $builder = new Builders();
        $company = new CompanyInfo;

        $validatedReq = $request->validatedOnly();

        $userInput = $request->only($user->getFillable());
        $userColumns = $user->getFillable();

        $companyInput = $request->get('company_info');
        $companyColumns = $company->getFillable();

        $userInput['password'] = bcrypt($userInput['password']);
        $userType = $request->input('userType');
        
        $user->is_terms_accepted  = $request->input('is_terms_accepted');
        $user->is_tutorial_viewed  = $request->input('is_tutorial_viewed');
        $user->associations = $request->input('associations');
        $user->certifications = $request->input('certifications');
        $user->references  = $request->input('references');
        


        foreach ($userColumns as $column) {
            if (array_key_exists($column, $userInput) && !empty($userInput[$column])
                && $column !== 'isSubcontractor'
                && $column !== 'isBuilder'
                && $column !== 'isAdmin'
                && $column !== 'userType'
                && $column !== 'trade'
                && $column !== 'password_confirmation'
                && $column !== 'token') {
                $user->$column = $userInput[$column];
            }
        }
        foreach ($companyColumns as $column2) {
            if (array_key_exists($column2, $companyInput)
                && !empty($companyInput[$column2])
                && $column2 !== 'isAdmin'
                && $column2 !== 'isBuilder'
                && $column2 !== 'userType'
                && $column2 !== 'trade'
                && $column2 !== 'isSubcontractor'
                && $column2 !== 'password_confirmation'
                && $column2 !== 'token') {
                $company->$column2 = $companyInput[$column2];
            }
        }

        try {
            $user->token = Password::getRepository()->createNewToken();
            $company->companySlug = str_slug(str_replace('&', 'and', $companyInput['company']));
            $company->uuid = GeneralHelpers\generateUniqueString("company_info", "uuid", 16);
            $company->logoURL = 'assets/images/no-image-found.png';
            if ($userType === 'subcontractor') {
                $trade = $validatedReq['trade_info']['scTradeID'];
                $user->isSubContractor = 1;
                $user->userType = 'subcontractor';
                $sc->scTradeID = $trade;
                $user->save();
                $sc->userID = $user->id;
                $sc->max_project_size = $validatedReq['trade_info']['max_project_size'];
                $sc->min_employee = $validatedReq['trade_info']['min_employee'];
                $sc->max_employee = $validatedReq['trade_info']['max_employee'];
                $sc->rating = $validatedReq['trade_info']['rating'];
                $sc->save();
                $user->assign('subcontractor');
            } else if ($userType === 'builder') {
                $user->isBuilder = 1;
                $user->userType = 'builder';
                $user->save();
                $user->assign('builder');
                $builder->userID = $user->id;
                $builder->save();
            } else {
                return response()->json(['error' => 'You are doing something you are unauthorized to do'], 401);
            }
        } catch (Exception $exception) {
            if ($user) {
                $user->delete();
            }
            if ($sc) {
                $sc->delete();
            }
            if ($builder) {
                $builder->delete();
            }
            return DBHelpers\returnDBError($exception);
        }
        try {
            $company->userID = $user->id;
            $count = CompanyInfo::where('companySlug', 'LIKE', '%' . $company->companySlug . '%')->count();
            if ($count > 0) {
                ++$count;
                $company->companySlug = $company->companySlug . $count;
            }
            $company->save();

            $profile = new Profile();
            $profile->userID = $user->id;
            $profile->save();

            for ($i = 0; $i < 8; $i++) {
                $profUploads = new ProfileUploads();
                $profUploads->userID = $user->id;
                $profUploads->profileID = $user->id;
                $profUploads->isLogo = 0;
                $profUploads->fileID = Uuid::generate();
                $profUploads->save();
            }
            $profUploads = new ProfileUploads();
            $profUploads->userID = $user->id;
            $profUploads->profileID = $user->id;
            $profUploads->isLogo = 1;
            $profUploads->fileURL = "assets/images/no-image-found.png";
            $profUploads->fileID = Uuid::generate();
            $profUploads->save();

            $profUploads = new ProfileUploads();
            $profUploads->userID = $user->id;
            $profUploads->profileID = $user->id;
            $profUploads->isLogo = 2;
            $profUploads->fileID = Uuid::generate();
            $profUploads->save();

            Bouncer::allow($user)->toManage($profile);

resources/views/dashboard/users/create.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Create User
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('users.index') }}">Users</a></li>
            <li class="active">Create User</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row" ng-app="userCreateApp" ng-controller="createCtrl" ng-if="!loading">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('users.index') }}"><i class="fa fa-angle-double-left"></i> Back to Users</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Create User</div>
                    <div class="pull-right">
                        <label class="form-check-label" for="verified" style="margin-right: 10px;">Verified </label>
                        <input type="checkbox" class="form-check-input" ng-model="user.verified" ng-true-value='1' ng-false-value='0'>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group">
                        <label>Email *</label>
                        <input type="text" class="form-control" ng-model="user.email">
                    </div>
                    <div class="form-group">
                        <label>Password *</label>
                        <input type="text" class="form-control" ng-model="user.password">
                    </div>
                    <div class="form-group">
                        <label>Password Confirmation *</label>
                        <input type="text" class="form-control" ng-model="user.password_confirmation">
                    </div>
                    <div class="form-group">
                        <label>User Type</label>
                        <select ng-model="user.userType" class="form-control">
                            <option value="builder">Builder</option>
                            <option value="subcontractor">Subcontractor</option>
                        </select>
                    </div>
                    <div class="form-group" ng-if="user.userType === 'subcontractor'">
                        <label>Trade</label>
                        <select ng-model="user.trade_info.scTradeID" class="form-control">
                            <option ng-repeat="sct in scts" ng-value="sct.id"><%sct.tradeName%></option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4" ng-if="user.userType === 'subcontractor'">
                            <label>Minimum Project Size</label>
                            <input type="number" class="form-control" min='1' ng-model="user.trade_info.max_project_size">
                        </div>
                        <div class="form-group col-md-3" ng-if="user.userType === 'subcontractor'">
                            <label>Min Employee</label>
                            <input type="number" class="form-control" min='1' ng-model="user.trade_info.min_employee">
                        </div>
                        <div class="form-group col-md-3" ng-if="user.userType === 'subcontractor'">
                            <label>Max Employee</label>
                            <input type="number" class="form-control" min='1' ng-model="user.trade_info.max_employee">
                        </div>
                        <div class="form-group col-md-2" ng-if="user.userType === 'subcontractor'">
                            <label>Rating</label>
                            <input type="number" class="form-control" min='0' max="100" ng-model="user.trade_info.rating">
                        </div>
                    </div>
                    <div class="business_info">
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" class="form-control" placeholder="Company Name" tabindex="6" ng-model='company.company'>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>Address 1</label>
                                <input type="text" class="form-control" placeholder="Address 1" tabindex="6" ng-model='company.address'>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Address 2</label>
                                <input type="text" class="form-control" placeholder="Address 2" tabindex="6" ng-model='company.address2'>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>City</label>
                                <input type="text" class="form-control" placeholder="City" tabindex="6" ng-model='company.city'>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Postal Code</label>
                                <input type="text" class="form-control" placeholder="Postal Code" tabindex="6" ng-model='company.postalCode'>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Province</label>
                                <input type="text" class="form-control" placeholder="Province" tabindex="6" ng-model='company.province'>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Business Phone Number</label>
                            <input type="text" class="form-control" placeholder="Business Phone Number" tabindex="6" ng-model='company.phoneNumber'>
                        </div>
                    </div>
                    <div class="company_contact">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>First Name</label>
                                <input type="text" class="form-control" placeholder="First Name" tabindex="6" ng-model='company.contactFirstName'>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Last Name</label>
                                <input type="text" class="form-control" placeholder="Last Name" tabindex="6" ng-model='company.contactLastName'>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Contacts Phone Number</label>
                            <input type="text" class="form-control" placeholder="Contacts Phone Number" tabindex="6" ng-model='company.phoneNumber2'>
                        </div>
                    </div>
                    <hr/>

 <div class="company_contact">                             
                       
                        <div class="form-group">
                            <label>Associations</label>
                            
                                <textarea class="form-control" placeholder="Associations" tabindex="6" ng-model='user.associations' ></textarea>
                        </div>

                        <div class="form-group">
                            <label>Certifications</label>
                             <textarea class="form-control" placeholder="Certifications" tabindex="6" ng-model='user.certifications' ></textarea>
                        </div>
                        <div class="form-group">
                            <label>References</label>
                            <textarea class="form-control" placeholder="References" tabindex="6" ng-model='user.references' ></textarea>
                        </div>

                         <div class="form-group">
                               <label>Is Tutorial Viewed </label>                                
                                <input type="checkbox" class="form-check-input" ng-model="user.is_tutorial_viewed" ng-true-value='1' ng-false-value='0'>
                            </div>

                          <div class="form-group">
                               <label>Terms Accepted</label>                                
                                <input type="checkbox" class="form-check-input" ng-model="user.is_terms_accepted" ng-true-value='1' ng-false-value='0'>
                            </div>   

                    </div>
                    <hr/>


                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-sm btn-primary" ng-click="save()">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_styles')
    <style>
        .business_info {
            background-color: rgba(0, 0, 0, 0.02);
            margin: 0px -10px;
            padding: 10px 10px;
        }
        .company_contact {
            padding-top: 10px;
        }
    </style>
@endsection
@section('after_scripts')
    <script>
    </script>
@endsection

@section('after_vendor_scripts')
    <script src="{{ asset('js/users/create.js') }}"></script>
@endsection

resources/views/dashboard/users/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Users
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Users</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Users ({{ count($users) }})</div>
                    <button type="button" class="btn btn-sm btn-primary pull-right" onclick="addUser()">Add User</button>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover" id='users'>
                        <thead>
                            <tr>
                            	<th>Contact Name</th>
                                <th>Email</th>
                                <th>Type</th>
                                <th>Verified</th>
                                <th>Trade</th>
                                <th>Minimum Project Size</th>
                                <th>Minimum Employee</th>
                                <th>Max Employee</th>
                                <th>Rating</th>
                                <th>Created at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            	@if($user->userType)
                                <tr>
                                	<td>{{ $user->company_info['contactFirstName']. ' '. $user->company_info['contactLastName'] }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->userType }}</td>
                                    <td>{{ $user->verified ? 'Yes' : 'No' }}
                                    <td>
                                        {{ $user->trade_info ? $user->trade_info['subcontractor_trades']['tradeName'] : ''}}
                                    </td>
                                    <td>
                                        {{ $user->trade_info ? '$ '. $user->trade_info['max_project_size'] : ''}}
                                    </td>
                                    <td>
                                        {{ $user->trade_info ? $user->trade_info['min_employee'] : ''}}
                                    </td>
                                    <td>
                                        {{ $user->trade_info ? $user->trade_info['max_employee'] : ''}}
                                    </td>
                                    <td>
                                        {{ $user->trade_info ? $user->trade_info['rating'] : ''}}
                                    </td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-danger pull-right remove" data-href="{{ route('users.destroy', $user->id) }}">
                                            <i class="fa fa-trash"></i> Delete
                                        </a>
                                        <a class="btn btn-xs btn-default pull-right" style="margin-right:10px;" href="{{ route('users.edit', $user->id) }}">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                    </td>
                                </tr>
                                @endif
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('after_styles')
	<style type="text/css">
		#users_filter {
            float: right;
		}
	</style>
@endsection
@section('after_scripts')
<script src="{{ asset('vendor/adminlte') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('vendor/adminlte') }}/plugins/datatables/dataTables.bootstrap.min.js"></script>

<script>
	$(function () {
		$("#users").DataTable();
    });

    var addUser = function() {
        location.href="{{ route('users.create') }}";
    }
</script>
@endsection